sources:
  # ─────────────────────────────
  # 來源 1：靜態（保留原本設定）
  - name: books_static
    type: static
    list_url: "https://books.toscrape.com/catalogue/page-1.html"
    item_selector: "article.product_pod"
    pagination:
      next_selector: "li.next a"
      max_pages: 10
    fields:
      id: "h3 a @ href"
      title: "h3 a"
      url: "h3 a @ href"
      author: ""
      category: ""
      date: ""
      price: "p.price_color"

  # ─────────────────────────────
  # 來源 2：LINE TODAY（動態）
  - name: linetoday_news_dynamic
    type: dynamic
    list_url: "https://today.line.me/tw/v2/tab/top"
    consent:
      click_selector_any:
        - "button:has-text('同意')"
        - "button:has-text('接受')"
      timeout_ms: 5000
    load_more:
      click_selector_any:
        - "button:has-text('載入更多')"
        - "button:has-text('看更多')"
        - "a:has-text('看更多')"
      times: 8
      pause_ms: 1000
    scroll:
      times: 8
      pause_ms: 900
      until_new_items: 10
    item_selector_any:
      - "a[data-article-id]"
      - "li[class*='ArticleListItem'] a"
      - "article a[href*='/detail/']"
    fields:
      id:
        any:
          - "a[data-article-id]"
          - "a"
      title:
        any:
          - "h3"
          - "span[class*='title']"
          - "div[class*='title']"
      url:
        any:
          - "a @ href"
      author:
        any:
          - "span[class*='publisher']"
          - "div[class*='source']"
          - "span[class*='source']"
      category:
        any:
          - "a[class*='category']"
          - "span[class*='category']"
      date:
        any:
          - "time @ datetime"
          - "span[class*='time']"
      price: ""
    postprocess:
      make_url_absolute_with_prefix: "https://today.line.me"
      normalize_whitespace: ["title","author","category"]
      dedup_key: ["id"]

